// api/calculator.js - Loan Repayment Calculator
module.exports = (req, res) => {
  let monthly_payment = 0, total_payable = 0, total_interest = 0, error = "", submitted = false;
  if (req.method === "POST") {
    const { principal, interest_rate, years } = req.body;
    const p = parseFloat(principal), r = parseFloat(interest_rate), y = parseInt(years);
    submitted = true;
    if (p <= 0 || y <= 0) {
      error = "Please enter valid positive numbers for the loan amount and duration.";
    } else {
      const mr = (r / 100) / 12, tm = y * 12;
      if (mr === 0) { monthly_payment = p / tm; total_payable = p; }
      else { monthly_payment = p * (mr * Math.pow(1 + mr, tm)) / (Math.pow(1 + mr, tm) - 1); total_payable = monthly_payment * tm; }
      total_interest = total_payable - p;
    }
  }
  const pVal = req.body?.principal || "1000.00", rVal = req.body?.interest_rate || "5.0", yVal = req.body?.years || "2";
  const fmt = (n) => "GHS " + n.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ",");
  const results = submitted && !error ? `<div class="space-y-4"><div class="p-4 bg-gray-50 rounded-lg border border-gray-100"><p class="text-xs text-gray-500 font-medium">Estimated Monthly Installment</p><p class="text-2xl font-bold text-[#1B365D] mt-1">${fmt(monthly_payment)}</p></div><div class="p-4 bg-gray-50 rounded-lg border border-gray-100"><p class="text-xs text-gray-500 font-medium">Total Interest Accrued</p><p class="text-xl font-semibold text-amber-600 mt-1">${fmt(total_interest)}</p></div><div class="p-4 bg-gray-50 rounded-lg border border-gray-100"><p class="text-xs text-gray-500 font-medium">Total Repayable Amount</p><p class="text-xl font-semibold text-[#00875A] mt-1">${fmt(total_payable)}</p></div></div>` : `<div class="h-48 flex items-center justify-center text-center text-gray-400"><p>Submit the form parameters to view calculated loan projections.</p></div>`;
  res.setHeader("Content-Type", "text/html");
  res.send(`<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Repayment Calculator - Campus Loan Portal</title><script src="https://cdn.tailwindcss.com"></script></head><body class="bg-[#F4F6F9] text-[#2C3E50] font-sans flex min-h-screen"><aside class="w-64 bg-[#1B365D] text-white hidden md:flex flex-col p-6 shadow-lg"><h1 class="text-xl font-bold tracking-wide mb-8">CampusLoan</h1><nav class="space-y-4"><a href="/dashboard" class="block py-2.5 px-4 rounded hover:bg-blue-800 transition">Dashboard</a><a href="/calculator" class="block py-2.5 px-4 rounded bg-blue-900 font-semibold">Repayment Calculator</a><a href="/" class="block py-2.5 px-4 rounded hover:bg-blue-800 transition">Home</a></nav></aside><main class="flex-1 p-8"><header class="mb-8"><h2 class="text-2xl font-bold text-[#1B365D]">Post-Graduation Repayment Simulator</h2><p class="text-sm text-gray-500 mt-1">Plan your finances ahead by modeling monthly deductions based on loan terms.</p></header>${error ? `<div class="mb-6 p-4 rounded-lg bg-red-50 border border-red-200 text-red-700 font-medium">${error}</div>` : ""}<div class="grid grid-cols-1 lg:grid-cols-2 gap-8"><section class="bg-white p-6 rounded-xl shadow-sm border border-gray-100"><h3 class="text-lg font-bold text-[#1B365D] mb-4">Simulation Parameters</h3><form action="/calculator" method="POST" class="space-y-4"><div><label class="block text-sm font-medium text-gray-700 mb-1">Loan Principal Amount (GHS)</label><input type="number" step="0.01" name="principal" required value="${pVal}" class="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-[#1B365D]"></div><div><label class="block text-sm font-medium text-gray-700 mb-1">Annual Interest Rate (%)</label><input type="number" step="0.1" name="interest_rate" required value="${rVal}" class="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-[#1B365D]"></div><div><label class="block text-sm font-medium text-gray-700 mb-1">Repayment Duration (Years)</label><input type="number" name="years" required value="${yVal}" class="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-[#1B365D]"></div><button type="submit" class="w-full bg-[#1B365D] text-white py-2.5 rounded-lg font-semibold hover:bg-blue-900 transition">Calculate Projections</button></form></section><section class="bg-white p-6 rounded-xl shadow-sm border border-gray-100 flex flex-col justify-between"><div><h3 class="text-lg font-bold text-[#1B365D] mb-4">Financial Summary</h3>${results}</div><div class="mt-6 pt-4 border-t text-xs text-gray-400">* Financial calculation methodology structured in coordination with departmental banking standards.</div></section></div></main></body></html>`);
};
